### ISSUE TITLE
Does this support browserlist?

### ISSUE THREAD

**Issue by thiagomajesk** [Modernizr/Modernizr#2537]
Hi! I was looking for a way to selectively enable/ disable some features based on browser version and I think it would be very handy to have something like [browserlist](https://github.com/browserslist/browserslist) integrated.

**Comment by MarkelFe** [comment]
Could you elaborate please? I mean, you could disable features based on the results of Modernizr tests. Or is that you want to test for different things depending on what browser accesses the website?

**Comment by thiagomajesk** [comment]
@MarkelFe Yes of course... 
By supporting Browserlist I mean supporting a subset of the notation in [this target list](https://github.com/browserslist/browserslist#full-list). I think it would be very handy to be able to do something like:

```css
/* Default */
.last-2-versions .blur {
    backdrop-filter: blur(10px);
}

/* Fallback */
not(.last-2-versions) .blur {
   background: transparent;
}

/* Corner cases */
.ie-6-8  .blur, .edge-16 .blur {
    background-color: rgba(255, 255, 255, 0.5);
}
```

For this specific scenario (using backdrop-filter as an example), the functionality may be supported by some browser and still have weird effects, like Edge 44 or not supported at all <=IE11. 
So you could whitelist/ blacklist what browser versions you want to target, instead of every target.
