### ISSUE TITLE
No-Touch

### ISSUE THREAD

**Issue by robcolburn** [Modernizr/Modernizr#855]
Need a way to target devices that do not support Touch because Mobiles don't like :hover.

http://www.nczonline.net/blog/2012/07/05/ios-has-a-hover-problem/

How:

``` js
if (! ("ontouchstart" in document.documentElement)) {
    document.documentElement.className += " no-touch";
}
```

via @bruceharris

Why:

``` css
.glow {
    background: #000;
    color: #fff;
}
.no-touch .glow:hover {
    background: #ff0;
    color: #000;
}
```

Still not perfect, but striving toward a solution.
